# Meta Data for SEO

## Homepage
title = "The integrative"
titleSeparator = "-"
titleAddition = "Let's get integrative together!"
description = "Linux, opensource and more integrated in the future"

## Open Graph
images = ["images.jpg"]
ogLocale = "en_US"
titleHome = "The integrative"

## Twitter Cards
twitterSite = "@theintegratives"
twitterCreator = "@theintegratives"

## JSON-LD
schemaLogo = "images.jpeg"
schemaTwitter = "https://twitter.com/theintegratives"
schemaLinkedIn = "https://www.linkedin.com/in/brightly/"
schemaGitHub = "https://github.com/theintegrative"
schemaSection = "insights"
schemaType = "Organization"

## Sitelinks Search Box
siteLinksSearchBox = true

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a> and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2020"

# Alert
alert = false
alertDismissable = true

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/theintegrative/theintegrative.net"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = true
lastMod = true

[sections]
  sectionNav = ["insights", "docs"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = ["insights", "docs"]
  searchSectionsIndex = ["insights", "docs"]
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = true
  scrollSpy = true # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = false
