variables:
  HOST: theintegrative.net
  DIR: public/

stages:
  - deploy

# TODO build job if dockerfile changes push and pull container image

deploy-job:
  stage: deploy
  image: theintegrative/hugo-ubuntu:0.2
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  ## Use ssh-keyscan to scan the keys of your private server. Replace gitlab.com
  - ssh-keyscan ${HOST} >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
    - hugo
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - rsync -avz public/ ${USER}@${HOST}:~/${DIR} --delete
    - ssh ${USER}@${HOST} "docker-compose down --remove-orphans && docker-compose up -d"
