variables:
  HOST: theintegrative.net

stages:
  - build
  - deploy

build-job:
  stage: build
  image: ubuntu
  script:
    - apt update
    - apt install hugo
    - hugo

deploy-job:
  stage: deploy
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  ## Use ssh-keyscan to scan the keys of your private server. Replace gitlab.com
  - ssh-keyscan ${HOST} >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  image: ubuntu
  script:
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - hugo && rsync -avz --delete public/ ${USER}@${HOST}:~/${DIR}
    - ssh ${USER}@s${HOST} "docker-compose down --remove-orphans && docker-compose up -d"
