name = "The Integrative"
license = ""
licenselink = ""
description = ""

homepage = "https://theintegrative.net"

tags = ["development", "devops", "engineering", "infrastructure", "linux", "integration"]
features = ["linux engineering", "continious integration", "development"]

[author]
  name = "The Integrative - Brightly Gourgel Santinho"
  homepage = "https://theintegrative.net"
